apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-simples
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web-green
            port:
              number: 80
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-path
  annotations: 
    nginx..ingress.kubernetes.oi/rewrite-target: / #my service will receice the "/" not "/blue"
  spec:
    ingressClassName: nginx
    rules:
    - http:
        paths:
        - path: /blue
          pathType: Prefix
          backend:
            service:
              name: web-blue
              port:
                number: 80
        - path: /green
          pathType: Prefix
          backend:
            service:
              name: web-green
              port:
                number: 80