apiVersion: v1
kind: ResourceQuota
metadata:
  name: contador-objetos
spec:
  hard:
    pods: "4" # counting the number os pods
    services: "2"
    secrets: "2"
    configmaps: "4"
    services.loadbalancers: "2"
    count/deployments.app: "2"
    count/replicaset.app: "2"