apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZ
    server: https://ef526102.k8s.ondigitalocean.com
  name: do-nyc3-aula-02
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJU
    server: https://localhost:6443
  name: k3d-mycluster
contexts:
- context:
    cluster: do-nyc3-aula-02
    user: do-nyc3-aula-02-admin
  name: do-nyc3-aula-02
- context:
    cluster: k3d-mycluster
    user: admin@k3d-mycluster
  name: k3d-mycluster
current-context: k3d-mycluster
kind: Config
preferences: {}
users:
- name: admin@k3d-mycluster
  user:
    client-certificate-data: LS0tLS1CRUd
    client-key-data: LS0tLS1CRUdJTiB
- name: do-nyc3-aula-02-admin
  user:
    token: dop_v1_954
