apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulador-do-caos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simulador-do-caos
  template:
    metadata:
      labels:
        app: simulador-do-caos
    spec:
      containers:
        - name: simulador-do-caos
          image: registry.k8s.io/busybox
          command:
          - /bin/sh
          - -c
          args:
          - sleep 600; touch /tmp/health; # simulate the file is not there when app starts.
          ports:
          - containerPort: 3000
          startupProbe:
            exec:
              command:
              - cat
              - /tmp/health        
          periodSeconds: 10
          failureThreshold: 30
  
---
apiVersion: v1
kind: Service
metadata:
  name: simulador-do-caos
spec:
  selector:
    app: simulador-do-caos
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    name: http
    protocol: TCP
    nodePort: 30000