apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-configuracao
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-configuracao
  template:
    metadata:
      labels:
        app: app-configuracao
    spec:
      containers:
      - name: app-configuracao
        image: kubedevio/app-variaveis-ambiente:v1
        ports:
        - containerPort: 3000
        env:
          - name: APP_NAME
            value: "My kubernetes application."
          - name: APP_VERSION
            value: "4.0"
          - name: APP_AUTHOR
            value: "Bozo Zoe"

---

apiVersion: v1
kind: Service
metadata:
  name: app-configuracao
spec:
  selector:
    app: app-configuracao
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30000
