apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulador-do-caos
spec:
  replicas: 20
  selector:
    matchLabels:
      app: simulador-do-caos
  template:
    metadata:
      labels:
        app: simulador-do-caos
    spec:
      containers:
      - name: simulador-do-caos
        image: kubedevio/simulador-do-caos:v1
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "0.2"
            memory: 64Mi
          limits:
            cpu: "0.4"
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: simulador-do-caos
spec:
  selector:
    app: simulador-do-caos
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    name: http
    protocol: TCP
    nodePort: 3000